#!/usr/bin/env python
import rospy
from base.base_runner import TestBase

""""
BASE INTERFACES
# sub
self._input_interface = {
    "robot_has_stopped"    : "/signal/calc/robot_has_stopped",
    "start_test"           : "/signal/ui/start_test",
    "interrupt_test"       : "/signal/ui/interrupt_test",
    "reset_test"           : "/signal/ui/reset_test"
}
# pub
self._output_interface = {
    "start_robot"          : "/signal/runner/start_robot",
    "stop_robot"            : "/signal/runner/stop_robot",
    "test_completed"       : "/signal/runner/test_completed",
    "test_failed"          : "/signal/runner/test_failed",
    "test_succeeded"       : "/signal/runner/test_succeeded",
    "start_test"           : "/signal/ui/start_test",
    "reset_test"           : "/signal/ui/reset_test",
    "interrupt_test"       : "/signal/ui/interrupt_test",
}
"""

class Test5(TestBase):
    def __init__(self, rate):
        
        extend_subscribers_dict = {
            "goal"  : "/signal/calc/robot_reached_goal",
            "robot_in_collision"  : "/signal/calc/robot_in_collision"
        }
        extend_publishers_dict = {
        }
        extend_param_list = {
            "goal_reach_timeout",
        }

        super(Test5, self).__init__(sub_dict = extend_subscribers_dict, \
        pub_dict = extend_publishers_dict, \
        param_list = extend_param_list, \
        rate = rate)

    def main(self):
        # Standard startup, robot started on return
        self.standardStartupSequence()

        # Wait until robot reaches goal or collides
        result = self.timedLoopFallbackOnFlags([ "goal", "robot_in_collision"],
                                                self.config_param['goal_reach_timeout'])
        if result == 0:
            # In test 5, we do not care if robot oscillates, as long as it reaches goal within time and without colliding
            rospy.logwarn(rospy.get_name() + ": Robot has reached goal, ending test in success!")
            self.testSucceeded()
        elif result == 1:
            rospy.logwarn(rospy.get_name() + ": Robot has collided, ending test in failure!")
            self.testFailed()
        elif result == self._RETURN_CASE_TIMED_OUT:
            rospy.logerr(rospy.get_name() + ": Robot did not reach goal in expected {}s, ending test in failure!!"
                    .format(self.config_param['goal_reach_timeout']))
            self.testFailed()
        elif result == self._RETURN_CASE_INTERRUPTED:
            return

        # TODO: Emulating UI responsibility Remove this once UI is integrated.
        self._publishers["start_test"].publish(self.buildNewBoolStamped(False))
        self.waitForReset()
        return


if __name__ == "__main__":
    try:
        rospy.init_node("Test5_runner", disable_signals=True)
        test = Test5(100)
        rospy.spin()
    except rospy.ROSException:
        pass
