#!/usr/bin/env python
import rospy
from base.base_runner import TestBase

""""
BASE INTERFACES
self._input_interface = {
    "robot_has_stopped"    : "/signal/calc/robot_has_stopped",
    "start_test"           : "/signal/ui/start_test",
    "interrupt_test"       : "/signal/ui/interrupt_test"
}

self._output_interface = {
    "start_robot"     : "/signal/runner/start_robot",
    "test_completed"  : "/signal/runner/test_completed",
    "test_failed"     : "/signal/runner/test_failed",
    "test_succeeded"  : "/signal/runner/test_succeeded"
}
"""

class Test1(TestBase):
    def __init__(self, rate):
        
        extend_subscribers_dict = {
            "robot_has_max_vel"  : "/signal/calc/robot_has_max_vel",
            "emergency"         : "/signal/robot/emergency"
        }
        extend_publishers_dict = {
            "stop_robot"     : "/signal/runner/stop_robot"
        }

        super(Test1, self).__init__(extend_subscribers_dict, extend_publishers_dict, rate = rate)
        self.main()

    def main(self):
        rospy.loginfo(rospy.get_name() + ": Waiting to start...")

        # Wait until start signal received
        while not rospy.is_shutdown():
            self._rate.sleep()
            if self.getSafeFlag("start_test"):
                self.startRecordingAndWait(3)
                rospy.loginfo(rospy.get_name() + ": Starting robot.")
                self._publishers["start_robot"].publish(self.buildNewBoolStamped(True))
                break
                
        # wait until robot reaches max velocity or robot emits emergency
        while not rospy.is_shutdown():
            self._rate.sleep()

            # If robot has reached max velocity
            if self.getSafeFlag("robot_has_max_vel"):
                rospy.loginfo(rospy.get_name() + ": Robot has reached max veloctiy, stopping it now.")
                # Stop robot
                self._publishers["start_robot"].publish(self.buildNewBoolStamped(False))
                self._publishers["stop_robot"].publish(self.buildNewBoolStamped(True))
                break

            # If robot emits emergency
            if self.getSafeFlag("emergency"):
                rospy.loginfo(rospy.get_name() + ": Robot has emitted emergency, assuming it stops now")
                self._publishers["start_robot"].publish(self.buildNewBoolStamped(False))
                break

            # If interrupted
            if self.getSafeFlag("interrupt_test"):
                rospy.logwarn(rospy.get_name() + ": Interrupted!! Exiting")
                self._publishers["start_robot"].publish(self.buildNewBoolStamped(False))
                self._publishers["test_failed"].publish(self.buildNewBoolStamped(True))
                self._publishers["test_completed"].publish(self.buildNewBoolStamped(True))
                return

        # Wait until robot actually stops or user hits interrupt
        while not rospy.is_shutdown():
            self._rate.sleep()

            if self.getSafeFlag("robot_has_stopped"):
                rospy.loginfo(rospy.get_name() + ": Robot has completely stopped. Test completed!")
                # Set test succeeded & test completed true
                self._publishers["test_succeeded"].publish(self.buildNewBoolStamped(True))
                self._publishers["test_completed"].publish(self.buildNewBoolStamped(True))
                break

            # If interrupted
            if self.getSafeFlag("interrupt_test"):
                rospy.logwarn(rospy.get_name() + ": Interrupted!! Exiting")
                self._publishers["start_robot"].publish(self.buildNewBoolStamped(False))
                self._publishers["test_failed"].publish(self.buildNewBoolStamped(True))
                self._publishers["test_completed"].publish(self.buildNewBoolStamped(True))
                return

if __name__ == "__main__":
    try:
        rospy.init_node("test1_runner", disable_signals=True)
        test = Test1(100)
        rospy.spin()
    except rospy.ROSException:
        pass