#!/usr/bin/env python
import rospy
from base.base_runner import TestBase
import enum

""""
BASE INTERFACES
# sub
self._input_interface = {
    "robot_has_stopped"    : "/signal/calc/robot_has_stopped",
    "start_test"           : "/signal/ui/start_test",
    "interrupt_test"       : "/signal/ui/interrupt_test",
    "reset_test"           : "/signal/ui/reset_test"
}
# pub
self._output_interface = {
    "start_robot"          : "/signal/runner/start_robot",
    "stop_robot"            : "/signal/runner/stop_robot",
    "test_completed"       : "/signal/runner/test_completed",
    "test_failed"          : "/signal/runner/test_failed",
    "test_succeeded"       : "/signal/runner/test_succeeded",
    "start_test"           : "/signal/ui/start_test",
    "reset_test"           : "/signal/ui/reset_test",
    "interrupt_test"       : "/signal/ui/interrupt_test",
}
"""

class Test1(TestBase):
    def __init__(self, rate):
        
        extend_subscribers_dict = {
            "emergency"            : "/signal/robot/emergency",
        }
        extend_publishers_dict = {
        }
        extend_param_list = {
            "emergency_wait_timeout",
            "acceleration_timeout",
            "decceleration_timeout",
        }

        super(Test1, self).__init__(sub_dict = extend_subscribers_dict, \
        pub_dict = extend_publishers_dict, \
        param_list = extend_param_list, \
        rate = rate)

    def main(self):
        # Standard startup, robot started on return
        self.standardStartupSequence()

        # Wait for emergency signal. Prototype example of timed waiting.
        rospy.loginfo(rospy.get_name() + ": Waiting for emergency signal within {}s"
            .format(self.config_param['emergency_wait_timeout']))
        result = self.timedLoopFallbackOnFlags(["emergency"], self.config_param['emergency_wait_timeout'])
        if result == self._RETURN_CASE_INTERRUPTED:
            return
        elif result == self._RETURN_CASE_TIMED_OUT:
            rospy.logwarn(rospy.get_name() + ": Did not get emergency signal in expected time. Test failed!")
            self.testFailed()
            # TODO: Emulating UI responsibility Remove this once UI is integrated.
            self._publishers["start_test"].publish(self.buildNewBoolStamped(False))
            self.waitForReset()
            return()
        else:
            rospy.loginfo(rospy.get_name() + ": Got emergency, stopping robot.")
            # Stop robot
            self.stopRobot()

        # Wait until robot actually stops
        result = self.timedLoopFallbackOnFlags(["robot_has_stopped"], self.config_param['decceleration_timeout'])
        if result == self._RETURN_CASE_INTERRUPTED:
            return
        elif result == self._RETURN_CASE_TIMED_OUT:
            rospy.logerr(rospy.get_name() + ": Robot did not stop in expected {}s, ending test in failure!!"
                    .format(self.config_param['decceleration_timeout']))
            self.testFailed()
        else:
            rospy.loginfo(rospy.get_name() + ": Robot has completely stopped. Test succeeded!")
            self.testSucceeded()

        # TODO: Emulating UI responsibility Remove this once UI is integrated.
        self._publishers["start_test"].publish(self.buildNewBoolStamped(False))
        # Once test completed, wait for reset
        self.waitForReset()
        return

if __name__ == "__main__":
    try:
        rospy.init_node("test1_emergency_runner", disable_signals=True)
        test = Test1(100)
    except rospy.ROSException:
        pass