#!/usr/bin/env python

# topic1 topic2 result
#  1        0       1
#  0        1       0

import rospy
from  command_interpreters.velocity_interpreter_class import VelocityInterpreterClass
from geometry_msgs.msg import Twist

# "/data/interpreter/velocity" remap to /cmd_vel
if __name__ == "__main__":
    rospy.init_node('velocity_interpreter')
    module_name = "/interpreters"
    ns = module_name + rospy.get_name()

    # define pub_msg
    pub_msg = {}
    msg = Twist()
    pub_msg["/stop"] = Twist()

    msg.linear.x = rospy.get_param(ns + '/max_vel')    
    pub_msg["/start"] = msg

    config_rate = ns + "/rate"
    rate = rospy.get_param(config_rate)
    
    interpreter = VelocityInterpreterClass(pub_msg = pub_msg, loop_rate_hz = rate)