#!/usr/bin/env python

# topic1 topic2 result
#  1        0       1
#  0        1       0

import rospy
from  command_interpreters.velocity_interpreter_class import VelocityInterpreterClass

# "/data/interpreter/velocity" remap to /cmd_vel
if __name__ == "__main__":
    rospy.init_node('velocity_interpreter')
    module_name = "/interpreters"
    ns = module_name + rospy.get_name()

    max_linear_x = rospy.get_param(ns + '/max_vel')    

    config_rate = ns + "/rate"
    rate = rospy.get_param(config_rate)
    
    interpreter = VelocityInterpreterClass(max_linear_x = max_linear_x, loop_rate_hz = rate)