calculators:
  robot_type: "turtlebot3_sim"
  test_type: "test3"

  folder_bagger_node:
    start_offset: 2 # Wait these many seconds before killing
    stop_offset: 2 # Wait these many seconds before killing
    whitelist:
    # Default whitelist: ["/signal/", "/data", "usb_cam", "/tf"]
    # Any topics which have one of these STRINGS in them will be added to the whitelist for recording,
      - hedge
      - ros
    blacklist:
    # Any WHITELISTED topics which have one of these STRINGS in them will be rejected for recording
      - compressed

  param_logger_node:
    start_offset: 1
    stop_offset: 0.5
    namespaces:
      - "calculators"

  robot_speed_logger:
    start_offset: 1.5 # Must be longer than folder bagger, since this tends to be created first.
    stop_offset: 0.1
    logged_data_title: "robot_speed"
    column_headers: ["Time", "Speed"]

  robot_pose_logger:
    start_offset: 1.5 # Must be longer than folder bagger, since this tends to be created first.
    stop_offset: 0.1
    logged_data_title: "robot_pose"
    column_headers: ["Time", "Seq",
                              "Pose.Position.x",
                              "Pose.Position.y",
                              "Pose.Position.z",
                              "Pose.Orientation.x",
                              "Pose.Orientation.y",
                              "Pose.Orientation.z",
                              "Pose.Orientation.w",
                              "Roll(deg)", "Pitch(deg)", "Yaw(deg)"]
