FloatLayout:

    MDLabel:
        id: my_label
        text: "ARAIG"
        halign: "center"
        size_hint: 1, 1
        pos_hint: {"center_x": .5, "center_y": 0.9}

    MDRaisedButton:
        text:"Start"
        size_hint: 0.1, 0.1
        pos_hint: {"center_x": .1, "center_y": 0.7}
        on_press: app.press_start(*args)

    MDRaisedButton:
        text:"Interrupt"
        size_hint: 0.1, 0.1
        pos_hint: {"center_x": .3, "center_y": 0.7}
        on_press: app.press_interrupt(*args)

    MDRaisedButton:
        text:"Reset"
        size_hint: 0.1, 0.1
        pos_hint: {"center_x": .3, "center_y": 0.5}
        on_press: app.press_reset(*args)

    Led:
        id: led_animated
        led_type: 'both'
        size_hint: 0.1, 0.1
        pos_hint: {"center_x": .5, "center_y": 0.7}
        source_on: 'media/fan.zip'
        source_off: 'media/fan.png'

    Led:
        id: led_typeboth1
        led_type: 'both'
        size_hint: 0.1, 0.1
        pos_hint: {"center_x": .7, "center_y": 0.7}
        source_off: 'shapes/basic_disc.png'
        source_on: 'media/no.png'
        color_off: [0,0,0,1]
        color_on: [1,0,0,1]

    Led:
        id: led_typeboth2
        led_type: 'both'
        size_hint: 0.1, 0.1
        pos_hint: {"center_x": .9, "center_y": 0.7}
        source_on: 'media/yes.png'
        source_off: 'shapes/basic_disc.png'
        color_off: [0,0,0,1]
        color_on: [0,1,0,1]

    Led:
        id: led_typeboth3
        led_type: 'both'
        size_hint: 0.1, 0.1
        pos_hint: {"center_x": .9, "center_y": 0.5}
        source_on: 'media/yes.png'
        source_off: 'shapes/basic_disc.png'
        color_off: [0,0,0,1]
        color_on: [0,1,0,1]


    MDLabel: 
        id: click_label
        text: "Pick Testing Setup:"
        halign: "center"
        size_hint: 1, 1
        pos_hint: {"center_x": .1, "center_y": 0.3}
        
    Spinner:
        id: spinner_id
        size_hint: 0.2, 0.1
        pos_hint: {"center_x": .3, "center_y": 0.3}
        text: "Testsetup"
        values: ["test1_breaking", "test1_emergency","test4", "test5_with_nav", "test5_without_nav"]
        on_text: app.spinner_clicked(spinner_id.text)
        
    MDLabel: 
        id: result1_label
        text: "value"
        halign: "center"
        size_hint: 1, 1
        pos_hint: {"center_x": .6, "center_y": 0.3}

    MDLabel: 
        id: result2_label
        text: "value"
        halign: "center"
        size_hint: 1, 1
        pos_hint: {"center_x": .6, "center_y": 0.2}

    MDLabel: 
        id: result1_v_label
        text: " "
        halign: "center"
        size_hint: 1, 1
        pos_hint: {"center_x": .8, "center_y": 0.3}    

    MDLabel:
        id: result2_v_label
        text: " "
        halign: "center"
        size_hint: 1, 1
        pos_hint: {"center_x": .8, "center_y": 0.2}