FloatLayout:

    MDLabel:
        id: my_label
        text: "ARAIG"
        halign: "center"
        size_hint: 1, 1
        pos_hint: {"center_x": .5, "center_y": 0.9}

    MDRaisedButton:
        text:"Start"
        size_hint: 0.1, 0.1
        pos_hint: {"center_x": .1, "center_y": 0.7}
        on_press: app.press_start(*args)

    MDRaisedButton:
        text:"Interrupt"
        size_hint: 0.1, 0.1
        pos_hint: {"center_x": .3, "center_y": 0.7}
        on_press: app.press_interrupt(*args)

    Led:
        id: led_animated
        led_type: 'both'
        size_hint: 0.1, 0.1
        pos_hint: {"center_x": .5, "center_y": 0.7}
        source_on: 'media/fan.zip'
        source_off: 'media/fan.png'

    Led:
        id: led_typeboth1
        led_type: 'both'
        size_hint: 0.1, 0.1
        pos_hint: {"center_x": .7, "center_y": 0.7}
        source_off: 'shapes/basic_disc.png'
        source_on: 'media/no.png'
        color_off: [0,0,0,1]
        color_on: [1,0,0,1]

    Led:
        id: led_typeboth2
        led_type: 'both'
        size_hint: 0.1, 0.1
        pos_hint: {"center_x": .9, "center_y": 0.7}
        source_on: 'media/yes.png'
        source_off: 'shapes/basic_disc.png'
        color_off: [0,0,0,1]
        color_on: [0,1,0,1]

    MDLabel: 
        id: click_label
        text: "Pick Testing Setup:"
        halign: "center"
        size_hint: 1, 1
        pos_hint: {"center_x": .3, "center_y": 0.5}
        
    Spinner:
        id: spinner_id
        size_hint: 0.2, 0.1
        pos_hint: {"center_x": .5, "center_y": 0.5}
        text: "Testsetup"
        values: ["Testsetup 1", "Testsetup 2","Testsetup 3", "Testsetup 4", "Testsetup 5"]
        on_text: app.spinner_clicked(spinner_id.text)
