#!/usr/bin/env python
import rospy
from difference.diff_pose_temporal import diffPoseTemporal
        
if __name__ == "__main__":
    rospy.init_node("diff_pose_temporal")

    module_name = "/calculators"
    ns = module_name + rospy.get_name()

    calc_displacement = diffPoseTemporal(rate = 100)