#!/usr/bin/env python
import rospy
from difference.diff_poses_spatial import diffPosesSpatial
        
if __name__ == "__main__":
    rospy.init_node("diff_poses_spatial")

    module_name = "/calculators"
    ns = module_name + rospy.get_name()

    calc_displacement = diffPosesSpatial(rate = 100)