#!/usr/bin/env python
import rospy
from comparators.edge_detector import edgeDetector
        
if __name__ == "__main__":
    rospy.init_node("edge_detector")

    module_name = "/calculators"
    ns = module_name + rospy.get_name()
    
    comparater_param = edgeDetector(rate = 100)