#!/usr/bin/env python

import sys
import os
from loggers.float_time_series_logger import FloatSeriesLoggerClass
import rospy

if __name__ == "__main__":
    rospy.init_node("float_series_logger")
    float_logger = FloatSeriesLoggerClass()