#!/usr/bin/env python

import sys
import os
from loggers.pose_time_series_logger import PoseSeriesLoggerClass
import rospy

if __name__ == "__main__":
    rospy.init_node("pose_series_logger")
    pose_logger = PoseSeriesLoggerClass()