#!/usr/bin/env python
import sys
import os
from loggers.rosparam_logger import RosparamLoggerClass
import rospy

if __name__ == "__main__":
    rospy.init_node("rosparam_logger_node")    
    rosparam_logger = RosparamLoggerClass()