name: CI
on: [push, pull_request]
jobs:
  industrial_ci:
    strategy:
      matrix:
        env:
          - {ROS_DISTRO: melodic, BUILDER: catkin_tools}
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      # Run industrial_ci
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{ matrix.env }}
